# Generated by Django 4.1.4 on 2022-12-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_variation_cartitem_variationitem'),
        ('store', '0004_rename_is_avtive_variation_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='VariationModel',
        ),
    ]
