# Generated by Django 4.1.4 on 2022-12-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_variation_cartitem_variationitem'),
        ('store', '0005_rename_variation_variationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariationModel',
            new_name='Variation',
        ),
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
