# Generated by Django 4.1.4 on 2022-12-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_variation_cartitem_variationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variationitem',
            new_name='variation',
        ),
    ]
